[package]
name = "blockchain-from-scratch"
version = "0.1.0"
edition = "2021"
authors = "Marcin Szałański"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
